
spring:

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true
    console:
      enabled: true
      path: /h2